feat: Rename verificationMethodId to kid [DEV-3670]
cheqd/did-registrar pull request #271
Opened 2024-02-19 09:54 UTC by lampkin-diet

2024-02-19 09:54 UTC, ankurdotb commented
Task linked: [DEV-3670 DID-Registrar: Move to kid from verificationMethodId](https://app.clickup.com/t/6600954/DEV-3670)

2024-02-19 10:27 UTC, DaevMithran requested changes

2024-02-19 10:27 UTC, DaevMithran commented on src/helpers/helpers.ts
> +			verificationMethodId: value.kid,
The key here should be change from `verificationMethodId` to `kid` right?

2024-02-19 10:28 UTC, DaevMithran requested changes

2024-02-19 10:28 UTC, DaevMithran commented on src/helpers/helpers.ts
> +			verificationMethodId: value.kid,
```suggestion
			kid: value.kid,
```

2024-02-20 17:52 UTC, Eengineer1 submitted a review, later dismissed
Looks good.

Approved.

2024-02-20 17:55 UTC, merged